# Generated by Django 5.2.17 on 2026-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_id', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('application_date', models.DateField(blank=True)),
                ('status', models.CharField(max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True)),
                ('notes', models.CharField(blank=True)),
            ],
        ),
    ]
